version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  rpi-bot:
    lang: go
    handler: ./rpi-bot
    image: ${IMAGE_NAME:-ghcr.io/alexellis/faasd-example:latest}
    # image: ghcr.io/alexellis/faasd-example:latest
