version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  rpi-events:
    lang: go
    handler: ./rpi-events
    image:  ghcr.io/${OWNER:-alexellis}/rpi-events:${TAG:-latest}
    environment:
      content_type:  "text/html"

  profile-page:
    lang: node16
    handler: ./profile-page
    image: ghcr.io/${OWNER:-alexellis}/profile-page:${TAG:-latest}

  repo-summary:
    lang: go
    handler: ./repo-summary
    image: ghcr.io/${OWNER:-alexellis}/repo-summary:${TAG:-latest}
    build_args:
      GO111MODULE: off
    environment:
      write_debug: true
      read_debug: true
      combined_output: false
      read_timeout: 10s
      write_timeout: 10s
    secrets:
    - repo-reader-token

