version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  rpi-bot:
    lang: go
    handler: ./rpi-bot
    image: ghcr.io/${OWNER:-:alexellis}/rpi-bot:${TAG:-:latest}
  rpi-events:
    lang: go
    handler: ./rpi-events
    image:  ghcr.io/${OWNER:-:alexellis}/rpi-events:${TAG:-:latest}
