version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  rpi-events:
    lang: go
    handler: ./rpi-events
    image:  ghcr.io/${OWNER:-alexellis}/rpi-events:${TAG:-latest}
    environment:
      content_type:  "text/html"
  profile-page:
    lang: node16
    handler: ./profile-page
    image: ghcr.io/${OWNER:-alexellis}/profile-page:${TAG:-latest}

