# name: release

# on:
#   push:
#     tags:
#       - '*'

# permissions:
#   actions: read
#   checks: write
#   contents: read
#   packages: read

# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#         with:
#           fetch-depth: 1
#       - name: Get faas-cli
#         run: curl -sLSf https://cli.openfaas.com | sudo sh
#       - name: Pull template definitions
#         run: faas-cli template pull
#       - name: Get TAG
#         id: get_tag
#         run: echo ::set-output name=TAG::latest-dev
#       - name: Get Repo Owner
#         id: get_repo_owner
#         run: >
#           echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} |
#           tr '[:upper:]' '[:lower:]')
#       - name: Login to Container Registry
#         uses: docker/login-action@v1
#         with:
#           username: ${{ github.repository_owner }}
#           password: ${{ secrets.GITHUB_TOKEN }}
#           registry: ghcr.io
#       - name: Login
#         run: >
#           echo ${{secrets.OPENFAAS_PASSWORD}} | 
#           faas-cli login --gateway ${{secrets.OPENFAAS_URL}} --password-stdin
#       - name: Deploy
#         run: >
#           OWNER="${{ steps.get_repo_owner.outputs.repo_owner }}"
#           TAG="${{ github.sha }}"
#           faas-cli deploy --gateway ${{secrets.OPENFAAS_URL}}
